Poizon/Controllers/CatalogController.cs
using System.Drawing;
using Microsoft.AspNetCore.Mvc;
using Poizon.Domain.Helpers;
using Poizon.Domain.Models;
using Poizon.Domain.ViewModel;
using Poizon.Services.Interfaces;

namespace Poizon.Controllers;

public class CatalogController : Controller
{
    private readonly IClothesService _clothesService;
    private readonly ICategoryService _categoryService;
    private readonly ISubCategoryService _subCategoryService;
    private readonly ISubSubCategoryService _subSubCategoryService;
    private readonly IBrandService _brandService;
    private readonly IStyleService _styleService;
    private readonly ISexService _sexService;

    public CatalogController(ISexService sexService, IStyleService styleService, IBrandService brandService, ISubSubCategoryService subSubCategoryService, IClothesService clothesService, ICategoryService categoryService, ISubCategoryService subCategoryService)
    {
        _clothesService = clothesService;
        _categoryService = categoryService;
        _subCategoryService = subCategoryService;
        _subSubCategoryService = subSubCategoryService;
        _brandService = brandService;
        _sexService = sexService;
        _styleService = styleService;
    }

    public async Task<IActionResult> ShowAll()
    {
        var clothes = await _clothesService.GetAllWithName();
        var baseResponseBrand = await _brandService.GetAll();
        var baseResponseSex = await _sexService.GetAll();
        var baseResponseStyle = await _styleService.GetAll();
        var category = await _categoryService.GetAll();
        ViewBag.Category = category.Data;
        ViewBag.Brand = baseResponseBrand.Data;
        ViewBag.Sex = baseResponseSex.Data;
        ViewBag.Style = baseResponseStyle.Data;
        ViewBag.Data = clothes.Data;
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> ShowWithFilters([FromBody]CatalogFilters model)
    {
        if (ModelState.IsValid)
        {
            var clothes = await _clothesService.GetAllByFilters(model);
            return PartialView("_ProductListPartial", clothes.Data);
        }
        return BadRequest();
    }

    [HttpGet]
    public async Task<JsonResult> GetSubcategories(long categoryId)
    {
        var baseResponse = await _subCategoryService.GetAll();
        var subCategories = baseResponse.Data.Where(x => x.CategoryId == categoryId);

        return Json(subCategories);
    }

    [HttpGet]
    public async Task<JsonResult> GetSubcategoriesByName(string name)
    {
        var baseResponseCategory = await _categoryService.GetCategoryByName(name);
        var baseResponse = await _subCategoryService.GetAll();
        var subCategories = baseResponse.Data.Where(x => x.CategoryId == baseResponseCategory.Data.Id);

        return Json(subCategories);
    }

    [HttpGet]
    public async Task<JsonResult> GetSubSubcategories(long subCategoryId)
    {
        var baseResponse = await _subSubCategoryService.GetAll();
        var subCategories = baseResponse.Data.Where(x => x.SubCategoryId == subCategoryId);

        return Json(subCategories);
    }

    public async Task<IActionResult> ProductDetails(long id)
    {
        var product = await _clothesService.GetByIdWithName(id);
        if (product == null)
        {
            return NotFound();
        }
        var listPhoto = new List<byte[]>
        {
            product.Data.Photo,
            product.Data.Photo1,
            product.Data.Photo2,
            product.Data.Photo3,
            product.Data.Photo4,
            product.Data.Photo5,
        };
        ViewBag.Photos = listPhoto;
        return View(product.Data);
    }

    [HttpGet]
    public async Task<IActionResult> AddClothes()
    {
        var baseResponseCategory = await _categoryService.GetAll();
        var baseResponseSex = await _sexService.GetAll();
        ViewBag.Sex = baseResponseSex.Data; 
        ViewBag.Category = baseResponseCategory.Data;
        return View();
    }


    [HttpPost]
    public async Task<IActionResult> AddClothes(ClothesWithName clothes, IFormFile photo, IFormFile photo1, IFormFile photo2,
        IFormFile photo3, IFormFile photo4, IFormFile photo5)
    {
        MakePhoto(clothes, photo, photo1, photo2, photo3, photo4, photo5);
        var baseResponse = await _clothesService.AddClothesByAdmin(clothes);
        return RedirectToAction("ProductDetails", new { id = baseResponse.Data.Id });
    }

    [HttpPost]
    public async Task<IActionResult> RewriteClothes(ClothesWithName clothesWithName)
    {
        var baseResponse = await _categoryService.GetAll();
        ViewBag.Category = baseResponse.Data;
        return View(clothesWithName);
    }

    [HttpPost]
    public async Task<IActionResult> UpdateClothes(ClothesWithName clothesWithName, IFormFile photo, IFormFile photo1, IFormFile photo2,
        IFormFile photo3, IFormFile photo4, IFormFile photo5)
    {
        MakePhoto(clothesWithName, photo, photo1, photo2, photo3, photo4, photo5);
        var baseResponse = await _clothesService.UpdateClothesByAdmin(clothesWithName);
        return RedirectToAction("ProductDetails", new { id = baseResponse.Data.Id });
    }


    private void MakePhoto(ClothesWithName clothes, IFormFile photo, IFormFile photo1, IFormFile photo2,
        IFormFile photo3, IFormFile photo4, IFormFile photo5)
    {
        if (photo != null)
        {
            using (var memoryStream = new MemoryStream())
            {
                photo.CopyTo(memoryStream);
                clothes.Photo = memoryStream.ToArray();
            }
        }

        if (photo1 != null)
        {
            using (var memoryStream = new MemoryStream())
            {
                photo1.CopyTo(memoryStream);
                clothes.Photo1 = memoryStream.ToArray();
            }
        }

        if (photo2 != null)
        {
            using (var memoryStream = new MemoryStream())
            {
                photo2.CopyTo(memoryStream);
                clothes.Photo2 = memoryStream.ToArray();
            }
        }

        if (photo3 != null)
        {
            using (var memoryStream = new MemoryStream())
            {
                photo3.CopyTo(memoryStream);
                clothes.Photo3 = memoryStream.ToArray();
            }
        }

        if (photo4 != null)
        {
            using (var memoryStream = new MemoryStream())
            {
                photo4.CopyTo(memoryStream);
                clothes.Photo4 = memoryStream.ToArray();
            }
        }

        if (photo5 != null)
        {
            using (var memoryStream = new MemoryStream())
            {
                photo5.CopyTo(memoryStream);
                clothes.Photo5 = memoryStream.ToArray();
            }
        }
    }
}

Poizon/Controllers/InfoController.cs
using Microsoft.AspNetCore.Mvc;

namespace Poizon.Controllers;

public class InfoController : Controller
{
    public IActionResult Index() => View();
}

Poizon/Controllers/MainController.cs
using Microsoft.AspNetCore.Mvc;
namespace Poizon.Controllers;

public class MainController : Controller
{
    public IActionResult Index() => View();

    public IActionResult Error() => View();
}

Poizon/Views/Shared/_Layout.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/css/site.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/js/site.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <header>
        <div class="header-content">
            <div class="logo">
                <a asp-controller="Main" asp-action="Index">Tishamarket</a>
            </div>
            <div class="links">
                <a asp-controller="Catalog" asp-action="ShowAll" style="padding-top: 3vh;">Каталог</a>
                <a asp-action="Index" asp-controller="Info" style="padding-top: 3vh;">О нас</a>
                <a href="#" class="cart-link"></a>
                @if (!User.Identity.IsAuthenticated)
                {
                    <a href="#" style="padding-top: 3vh;" class="login-button">Вход</a>
                }
                else
                {
                    <div class="circle-link">
                        <div class="dropdown-content">
                            <div class="dropdown-item">
                                <a asp-action="ShowUserInfo" asp-controller="Account">Личный кабинет</a>
                            </div>
                            <div class="dropdown-item">
                                <a asp-action="Logout" asp-controller="Account">Выход</a>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </header>

    <div class="registration-overlay">
        <div class="registration-form-container">
            <div class="close-button">&times;</div>

        </div>
    </div>

    <div class="registration-overlay">
        <div class="registration-form-container">
            <div class="close-button">&times;</div>
            <h2 class="form-title">Вход:</h2>
            <form class="registration-form" id="loginForm" method="POST" asp-controller="Account" asp-action="Login">
                <div class="form-group">
                    <label for="email">E-mail:</label>
                    <input type="email" id="email" placeholder="Введите электронную почту" required>
                </div>
                <div class="form-group">
                    <label for="password">Пароль:</label>
                    <input type="password" id="password" placeholder="Введите пароль" required>
                </div>
                <button type="submit" class="submit-button">Войти</button>
            </form>
            <p class="registration-link">Нет аккаунта? <a asp-action="Register" asp-controller="Account" class="registration-link-text">Регистрируйся</a></p>
        </div>
    </div>
    <script>
        $(document).ready(function () {
            // Открытие формы регистрации
            $(".login-button").on("click", function () {
                // Отправка GET-запроса на сервер
                $.ajax({
                    url: '@Url.Action("Login", "Account")', // URL для метода Login в AccountController
                    type: "GET",
                    success: function (data) {
                        // При успешном получении данных, отображаем их в registration-overlay
                        $(".registration-overlay").fadeIn();
                        $(".registration-form-container").css("right", "0");
                        $(".registration-form-container").html(data); // Заменяем содержимое контейнера полученными данными
                    },
                    error: function () {
                        // Обработка ошибки, если не удалось получить данные
                        alert("Ошибка при загрузке формы входа.");
                    }
                });
            });
            $(".close-button").on("click", function () {
                $(".registration-overlay").fadeOut();
                $(".registration-form-container").css("right", "-400px");
            });
        });
    </script>

    <div class="cart-overlay">
        <div class="cart-container">
            <div class="close-button">&times;</div>
            <h2 class="cart-title">Корзина</h2>
            
        </div>
    </div>
    <style>

    </style>

    <div>
        @RenderBody()
    </div>
    <footer style="padding-top: 3vh;">
        <div class="items">
            <div class="links">
                <a href="#" class="link">
                    <img src="../../../img/telega.png" alt="Link 2">
                </a>
            </div>
            <p class="footer-text">© 2023 Tishamarket</p>
        </div>
    </footer>

    <style>
        .registration-link {
            text-align: center;
            margin-top: 10px;
            text-decoration: none;
            font-family: "Grotesk";
        }

        .registration-link-text {
            align-content: center;
            color: blue;
            text-decoration: none;
            font-family: "Grotesk";
            /* Дополнительные стили по вашему выбору */
        }

        .circle-link {
            position: relative;
            display: inline-block;
            width: 50px;
            height: 50px;
            border-radius: 50%;
            background-color: #ccc;
            text-align: center;
            line-height: 50px;
            font-size: 24px;
            text-decoration: none;
            color: #fff;
            font-weight: bold;
        }

        .dropdown-content {
            position: absolute;
            top: 100%;
            left: 0;
            display: none;
            border-radius: 5px;
            color: black;
        }

        .circle-link:hover .dropdown-content {
            display: block;
        }

        .dropdown-item {
            display: block;
            font-family: "Grotesk";
            font-size: 14px;
        }

            .dropdown-item a {
                text-decoration: none;
                color: #333;
            }

                .dropdown-item a:hover {
                    color: #696969;
                }
    </style>

</body>
</html>