Poizon/Controllers/MainController.cs
using Microsoft.AspNetCore.Mvc;
namespace Poizon.Controllers;

public class MainController : Controller
{
    public IActionResult Index() => View();

    public IActionResult Error() => View();
}

Poizon/Controllers/OrderController.cs
using System.Text;
using System.Text.Json;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Poizon.Domain.Helpers;
using Poizon.Domain.ViewModel;
using Poizon.Services.Interfaces;
using Telegram.Bot;
using Telegram.Bot.Types;
using Telegram.Bot.Types.Enums;

namespace Poizon.Controllers;

public class OrderController : Controller
{
    private readonly IOrderService _orderService;
    private readonly IClothesService _clothesService;
    private readonly IOrderClothesService _orderClothesService;
    private readonly IUserService _userService;
    private readonly IConfiguration _configuration;
    private readonly ITelegramBotClient _telegramBot;
    public OrderController(IConfiguration configuration, IClothesService clothesService, IUserService userService, IOrderService orderService, IOrderClothesService orderClothesService)
    {
        _configuration = configuration;
        _orderClothesService = orderClothesService;
        _orderService = orderService;
        _userService = userService;
        _clothesService = clothesService;
        _telegramBot = new TelegramBotClient(_configuration["TelegramBotToken"]);
    }

    [Authorize]
    [HttpPost]
    public async Task<IActionResult> AddToBasket(ClothesWithName clothesWithName)
    {
        var cloth = await _clothesService.GetById(clothesWithName.Id);
        clothesWithName.Photo = cloth.Data.Photo;
        var cartJson = HttpContext.Session.GetString("Cart");
        var cart = string.IsNullOrEmpty(cartJson) ? new List<ClothesWithName>() : JsonSerializer.Deserialize<List<ClothesWithName>>(cartJson);

        // Проверяем, есть ли уже товар с таким Id в корзине
        var existingItem = cart.FirstOrDefault(item => item.Id == clothesWithName.Id);
        if (existingItem != null)
        {
            // Если товар уже есть в корзине, увеличиваем значение Count
            existingItem.Count++;
        }
        else
        {
            // Если товара с таким Id нет в корзине, добавляем его
            clothesWithName.Count = 1;
            cart.Add(clothesWithName);
        }

        // Сохраните обновленную корзину в сеансе
        var updatedCartJson = JsonSerializer.Serialize(cart);
        HttpContext.Session.SetString("Cart", updatedCartJson);

        return RedirectToAction("ProductDetails", "Catalog", new { id = clothesWithName.Id });
    }


    [Authorize]
    public IActionResult ShowBasket()
    {
        // Получите текущую корзину из сессии
        var cartJson = HttpContext.Session.GetString("Cart");
        var cart = string.IsNullOrEmpty(cartJson) ? new List<ClothesWithName>() : JsonSerializer.Deserialize<List<ClothesWithName>>(cartJson);

        // Передайте список корзины в представление
        return PartialView("_ShowBasketPartial", cart);
    }

    [Authorize]
    [HttpPost]
    public IActionResult RemoveFromBasket(long id)
    {
        var cartJson = HttpContext.Session.GetString("Cart");
        var cart = string.IsNullOrEmpty(cartJson) ? new List<ClothesWithName>() : JsonSerializer.Deserialize<List<ClothesWithName>>(cartJson);

        // Находим товар с заданным Id в корзине и удаляем его
        var itemToRemove = cart.FirstOrDefault(item => item.Id == id);
        if (itemToRemove != null)
        {
            cart.Remove(itemToRemove);
        }

        // Сохраняем обновленную корзину в сессии
        var updatedCartJson = JsonSerializer.Serialize(cart);
        HttpContext.Session.SetString("Cart", updatedCartJson);

        return PartialView("_ShowBasketPartial", cart); // Возвращаем успешный результат запроса
    }

    [HttpGet]
    public IActionResult MakeOrder(int price)
    {
        ViewBag.Price = price;
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> MakeOrder(UserViewModel userViewModel)
    {
        var s = FormatTelegramMessage(userViewModel).ToString();
        await _telegramBot.SendTextMessageAsync("950000237", s, parseMode: ParseMode.Html);

        return View("Commit");
    }


    private StringBuilder FormatTelegramMessage(UserViewModel userViewModel)
    {
        var cartJson = HttpContext.Session.GetString("Cart");
        var cart = string.IsNullOrEmpty(cartJson) ? new List<ClothesWithName>() : JsonSerializer.Deserialize<List<ClothesWithName>>(cartJson);
        var builder = new StringBuilder();
        foreach(var item in cart)
        {
            builder.Append($@"Название: {item.SubSubCategoryName}
Бренд: {item.BrandName}
Модель: {item.ModelName}
Количество: {item.Count}
Размер: {item.SizeName}
Одежда: {item.SexName}
Стиль: {item.StyleName}

");

        }
        builder.Append($@"Номер телефона: {userViewModel.PhoneNumber}
Ник в телеграм: {userViewModel.TelegramName}
Ссылка на ВК: {userViewModel.Vk}
Адрес доставки: {userViewModel.Address}
Комментарий к заказу: {userViewModel.Comment}
Итоговая стоимость: {userViewModel.Price}");
        return builder;
    }
}

Poizon/Views/Order/Commit.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/site.css">
    <title>Заказ оформлен</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f7f7f7;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }

        .container {
            text-align: center;
            background-color: #ffffff;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .checkmark {
            border-radius: 50%;
            display: inline-block;
            width: 120px;
            height: 120px;
            border: 5px solid #00b300;
            animation: drawCheck 0.6s ease;
            position: relative;
        }

            .checkmark:after {
                content: '';
                position: absolute;
                top: 50%;
                left: 25px;
                width: 30px;
                height: 60px;
                border: solid #00b300;
                border-width: 0 7px 7px 0;
                transform: translateY(-50%) rotate(45deg);
            }

        .message {
            font-size: 24px;
            font-weight: bold;
            color: #00b300;
            margin-top: 20px;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="checkmark"></div>
        <div class="message">Заказ оформлен и с вами скоро свяжутся</div>
    </div>
    <div class="login-link">
        <a asp-controller="Main" asp-action="Index" style="padding-top: 3vh; text-decoration:none; font-family:'Grotesk';" class="login-button">На главную</a>
    </div>
</body>

</html>

Poizon/Views/Order/MakeOrder.cshtml
@using Poizon.Domain.ViewModel;
@model UserViewModel;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Оформление заказа";
}

<form id="order-form" method="post" asp-action="MakeOrder" asp-controller="Order">
    <div>
        <label for="phone">Номер телефона</label>
        <input type="text" id="phone"  asp-for="PhoneNumber" required>
    </div>
    <div>
        <label for="telegram">Ник в телеграм</label>
        <input type="text" id="telegram" asp-for="TelegramName" >
    </div>
    <div>
        <label for="vk">Ссылка на ВК</label>
        <input type="text" id="vk" asp-for="Vk" >
    </div>
    <div>
        <label for="address">Адрес доставки </label>
        <input type="text" id="address" asp-for="Address"  required>
    </div>
    <div>
        <label for="comment">Комментарий к заказу</label>
        <textarea id="comment" asp-for="Comment"></textarea>
        <input type="text" id="address" asp-for="Price" value="@ViewBag.Price" hidden>
    </div>
    <button type="submit">Заказать</button>
</form>
<div id="total-price" style="display: none;">Итоговая стоимость: @ViewBag.Price ₽</div>
<style>
    body {
        background-color: #f7f7f7;
        font-family: Arial, sans-serif;
        color: #333;
    }

    h2 {
        text-align: center;
        color: #444;
    }

    form {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    label {
        display: block;
        margin-bottom: 8px;
        color: #444;
    }

    input[type="text"],
    textarea {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        margin-bottom: 20px;
    }

    textarea {
        height: 100px;
    }

    button {
        background-color: #333;
        color: #fff;
        border: none;
        border-radius: 4px;
        padding: 10px 20px;
        cursor: pointer;
        font-size: 16px;
        transition: background-color 0.3s;
    }

        button:hover {
            background-color: #555;
        }
    #total-price {
        text-align: center;
        font-size: 24px;
        font-weight: bold;
        color: #555;
        margin-top: 20px;
        padding: 10px;
        border: 2px solid #555;
        border-radius: 4px;
        background-color: #f7f7f7;
    }
</style>

Poizon/Views/Order/_ShowBasketPartial.cshtml
@using Poizon.Domain.Helpers;
@model List<ClothesWithName>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<div class="cart-container">
    <div class="close-button">&times;</div>
    <h2 class="cart-title">Корзина</h2>
    @foreach (var item in Model)
    {
        string base64Image = Convert.ToBase64String(item.Photo);
        string imageSrc = string.Format("data:image/png;base64,{0}", base64Image);
        <div class="cart-items">
            <ul class="cart-list">
                <li class="cart-item">
                    <div class="cart-item-image">
                        <img src="@imageSrc" alt="Product 1">
                    </div>
                    <div class="cart-item-details">
                        <div class="cart-item-title">@item.SubSubCategoryName @item.BrandName</div>
                        <div class="cart-item-quantity" style="padding-bottom: 1vh; padding-top: 1vh;">
                            <button class="quantity-btn minus-btn" data-id="@item.Id">-</button>
                            <input type="number" value="@item.Count" class="custom-input" data-id="@item.Id" data-price="@item.Price">
                            <button class="quantity-btn plus-btn" data-id="@item.Id">+</button>
                        </div>
                        <div class="cart-item-price">Цена: @item.Price ₽</div>
                        <a href="#" class="cart-item-remove-btn" data-id="@item.Id" style="color:red; text-decoration:none; font-family:'Grotesk';">Удалить</a>
                    </div>
                </li>
            </ul>
        </div>
    }

    <div class="total">Итого: $0</div>
    <button class="checkout-button">Оформить заказ</button>
</div>



<style>
    .minus-btn {
        background-color: #8e8e8e;
        color: #ffffff;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 14px;
        width: 25px;
        height: 25px;
    }

    .plus-btn {
        background-color: #8e8e8e;
        color: #ffffff;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 14px;
        width: 25px;
        height: 25px;
    }

    .quantity-btn:hover {
        background-color: #c1c1c1;
    }

    .custom-input {
        margin-left: 1vh;
        margin-right: 1vh;
        -moz-appearance: textfield;
        -webkit-appearance: none;
        appearance: none;
        text-align: center;
        border: 1px solid #ccc;
        border-radius: 5px;
        width: 25px;
        font-size: 13px;
        height: 25px;
    }

    .custom-input {
        -moz-appearance: textfield;
        -webkit-appearance: none;
        appearance: none;
        padding: 0;
        text-align: center;
    }
</style>